# Generated by Django 5.1.2 on 2024-11-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_loan_options_remove_gamer_usersname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='boardgame_images/'),
        ),
    ]
