# Generated by Django 5.1.2 on 2024-11-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_boardgame_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardgame",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="returned",
            field=models.BooleanField(default=False),
        ),
    ]
