# Generated by Django 5.1.2 on 2024-11-19 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_boardgame_is_available_loan_returned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardgame',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'boardgames'},
        ),
        migrations.RemoveField(
            model_name='loan',
            name='return_by',
        ),
    ]
